server:
  port: 8080

management:
  port: 9000

endpoints:
  health:
    sensitive: false
  metrics:
    sensitive: false
  mappings:
    sensitive: false

security:
  basic:
    enabled: false

spring:
  datasource:
    driverClassName: oracle.jdbc.driver.OracleDriver
    max-active: 5
    initial-size: 1
    max-idle: 5
    min-idle: 1
    validation-query: select 1 from dual
